
name: rrdm-shh
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.6
  - pip
  - jupyter
  - nb_conda_kernels
  - samtools
  - bcftools
  - htslib
  - snakemake >=5.0
  - pysam >=0.15
  - pandas >=0.25
  - psutil
  - coverage >=4.5.3
  
  - pip:
    - pylexibank
    - pyconcepticon
    - pyglottolog
    - pyclts
    - pycldf
    - cldfbench
